@startuml

title UC-4: Create a Course Task

|User|
    start
    :Navigate to courses page;

|System|
    :Display Courses page;

|User|
    :Select and open a course from the list;

|System|
    :Display details of the user-selected course page;

|User|
    :Choose "Add task";

|System|
    :Display a course task form to enter task details;

|User|
    :Enter task name and deadline (Date);

|System|
    :Validate input;
    if (Valid?) then (yes)
        :Store task for course;
        :Display newly added task in list;
        stop
    else (no)
        :Show validation errors;
        :Show course task form with preserved entries;
        note right
            emphasize invalid values and focus first invalid field
        end note
        stop
    endif

@enduml
